# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171026_2104'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='traveler', to='login_app.User'),
        ),
    ]
