# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_planner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
